# Generated by Django 4.0.3 on 2022-06-12 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
