# Generated by Django 4.0.3 on 2022-06-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_notification_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price_step',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
