# Generated by Django 4.0.3 on 2022-06-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_listing_price_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
