# Generated by Django 4.0.3 on 2022-07-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_bid_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
